### ISSUE TITLE
[ WARN:0@0.390] global /io/opencv/modules/dnn/src/dnn.cpp (1483) setUpNet DNN module was not built with CUDA backend; switching to CPU

### ISSUE THREAD

**Issue by BraholliKristi** [Asadullah-Dal17/Yolov4-Detector-and-Distance-Estimator#10]
[ WARN:0@0.390] global /io/opencv/modules/dnn/src/dnn.cpp (1483) setUpNet DNN module was not built with CUDA backend; switching to CPU
Traceback (most recent call last):
  File "/home/braholli/Documents/Yolov4-Detector-and-Distance-Estimator-master/DistanceEstimation.py", line 72, in <module>
    mobile_data = object_detector(ref_mobile)
  File "/home/braholli/Documents/Yolov4-Detector-and-Distance-Estimator-master/DistanceEstimation.py", line 42, in object_detector
    label = "%s : %f" % (class_names[classid[0]], score)
IndexError: invalid index to scalar variable.

**Comment by Asadullah-Dal17** [comment]
Make sure to choose the correct environment, while running the code.

**Comment by hfatima08** [comment]
what do you mean by choosing the correct environment? What should i do to solve this issue? I'm using pycharm to run your code.

**Comment by Asadullah-Dal17** [comment]
a python Virtual Envnieorment in which you have installed required version of opencv

**Comment by hfatima08** [comment]
but the version you have mentioned is not being installed in the environment

**Comment by Asadullah-Dal17** [comment]
have you got any specific error message while installation process?

**Comment by vlasov01** [comment]
Hi,
I've got the same error. I've applied an answer from https://stackoverflow.com/questions/32978575/how-to-fix-indexerror-invalid-index-to-scalar-variable in three places.
But I think without CUDA it is too slow for my RPi4.
And I got another error:
[h264 @ 0x10ad7e20] error while decoding MB 45 2, bytestream -13
Traceback (most recent call last):
  File "/home/swim/Yolov4-Detector-and-Distance-Estimator/DistanceEstimation.py", line 92, in <module>
    data = object_detector(frame)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/swim/Yolov4-Detector-and-Distance-Estimator/DistanceEstimation.py", line 35, in object_detector
    classes, scores, boxes = model.detect(image, CONFIDENCE_THRESHOLD, NMS_THRESHOLD)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.6.0) ./modules/imgproc/src/resize.cpp:4052: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
